### ISSUE TITLE
Traceback (most recent call last):Using python 3.6 for evaluation

### ISSUE THREAD

**Issue by hjyai94** [hjkuijf/wmhchallenge#3]
Traceback (most recent call last):
  File "/home/nir/h_python1/evaluation.py", line 199, in <module>
    do()
  File "/home/nir/h_python1/evaluation.py", line 26, in do
    h95 = getHausdorff(testImage, resultImage)
  File "/home/nir/h_python1/evaluation.py", line 124, in getHausdorff
    np.transpose(np.flipud(np.nonzero(hTestArray))).astype(int))
  File "/opt/anaconda/envs/nir-gpu/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 132, in apply_along_axis
    res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
  File "/opt/anaconda/envs/nir-gpu/lib/python3.6/site-packages/SimpleITK/SimpleITK.py", line 3815, in TransformIndexToPhysicalPoint
    return _SimpleITK.Image_TransformIndexToPhysicalPoint(self, index)
TypeError: in method 'Image_TransformIndexToPhysicalPoint', argument 2 of type 'std::vector< int64_t,std::allocator< int64_t > > const &'

_Originally posted by @NirDiamant in https://github.com/hjkuijf/wmhchallenge/issues/1#issuecomment-397318897_

**Comment by hjyai94** [comment]
Hi, hjkuijf
I want to use your script in python3.6 to evaluate my segmentation result, but I have an error just as NirDiamant mentioned. Can you give me some advice to fix the error in python3.6?  Or, how can I change code below to compute the Hausdorff Distance that is same as your script? 
```
hausdorffcomputer = sitk.HausdorffDistanceImageFilter()
hausdorffcomputer.Execute(testImage , resultImage)
res = hausdorffcomputer.GetAverageHausdorffDistance()
```

**Comment by hjkuijf** [comment]
The code in this repo is for Python 2.7. For another MICCAI challenge, we have updated the code to work in Python 3 as well. You can find it here: https://github.com/hjkuijf/MRBrainS18/blob/master/evaluation.py#L114 . Note that it is slightly different, because the MRBrainS18 challenge has multiple labels whereas the WMH challenge has only one.

You should be able to modify the code easily. If you have done so, feel free to send a pull request and I'll merge it with this repo.
